### ISSUE TITLE
For when JS is disabled 

### ISSUE THREAD

**Issue by oliviaguest** [jordnkr/collapsible#5]
It might be useful to others too to add this to pages that make use of collapsible. This allows graceful degradation when no javascript is allowed (like on some mobile browsers):

``` html
<noscript>
   <style>
      .collapse-container > :nth-child(even) {
         display: block;
      }
   </style>
</noscript>
```

**Comment by jordnkr** [comment]
Added the snippet to the README mentioning that this is possible. Will add to gh-pages content if/when that is updated.
